name: tapandgo_poc
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: '>=3.5.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  cpay_sdk_plugin:
    git:
      url: https://github.com/wiratsil/cpay_sdk_plugin.git

  arke_sdk_flutter:
    git:
      url: https://github.com/wiratsil/arke_sdk_flutter.git

  http: ^1.1.0
  uuid: ^4.2.0
  shared_preferences: ^2.2.0
  wakelock_plus: ^1.3.3
  permission_handler: ^11.3.1
  socket_io_client: ^2.0.3+1
  network_info_plus: ^5.0.0
  geolocator: ^14.0.2
  mobile_scanner: ^5.1.0
  sqflite: ^2.3.0
  path: ^1.8.3
  qr_flutter: ^4.1.0
  mqtt_client: ^10.2.0
  package_info_plus: ^8.0.0
  audioplayers: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  geolocator_android: 4.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/BMTA_Logo.png
    - assets/audio/
